name: Auto Update TOC

on:
  push:
    branches:
      - main

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
          COMMIT_MESSAGE: "🤖 自动更新目录"

